//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalProject.Models.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand Name.
        /// </summary>
        public static string brandName {
            get {
                return ResourceManager.GetString("brandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string mainCategoryName {
            get {
                return ResourceManager.GetString("mainCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Photo.
        /// </summary>
        public static string mainCategoryPhoto {
            get {
                return ResourceManager.GetString("mainCategoryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max length is 50.
        /// </summary>
        public static string mainCategoryValidation {
            get {
                return ResourceManager.GetString("mainCategoryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must choose main category.
        /// </summary>
        public static string mandatoryMainCategoryforProduct {
            get {
                return ResourceManager.GetString("mandatoryMainCategoryforProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must choose main category.
        /// </summary>
        public static string mandatoryMainCategoryforSubCategory {
            get {
                return ResourceManager.GetString("mandatoryMainCategoryforSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must choose sub category.
        /// </summary>
        public static string mandatorySubCategoryforProduct {
            get {
                return ResourceManager.GetString("mandatorySubCategoryforProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Add Date.
        /// </summary>
        public static string ProductAddDate {
            get {
                return ResourceManager.GetString("ProductAddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Color.
        /// </summary>
        public static string ProductColor {
            get {
                return ResourceManager.GetString("ProductColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Discount.
        /// </summary>
        public static string ProductDiscount {
            get {
                return ResourceManager.GetString("ProductDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Photo.
        /// </summary>
        public static string ProductPhoto {
            get {
                return ResourceManager.GetString("ProductPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Quantity.
        /// </summary>
        public static string ProductQuantity {
            get {
                return ResourceManager.GetString("ProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product SubCategory.
        /// </summary>
        public static string ProductSubCategory {
            get {
                return ResourceManager.GetString("ProductSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string subCategoryName {
            get {
                return ResourceManager.GetString("subCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Photo.
        /// </summary>
        public static string subCategoryPhoto {
            get {
                return ResourceManager.GetString("subCategoryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max length is 50.
        /// </summary>
        public static string subCategoryValidation {
            get {
                return ResourceManager.GetString("subCategoryValidation", resourceCulture);
            }
        }
    }
}
